service: hello-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: ruby2.5

plugins:
  - serverless-plugin-canary-deployments

custom:
deploymentSettings:
  stages:
    - prod

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      # type: AllAtOnce
      alias: Hello